# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chatbot_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1162, 760)
        MainWindow.setStyleSheet("#centralwidget,\n"
"#input_frame{\n"
"background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#MainWindow QMainWindow{\n"
"    background-color: rgb(0, 0, 0);\n"
"\n"
"}\n"
"\n"
"#side_widget QPushButton{\n"
"text-align: left;\n"
"background:transparent;\n"
"}\n"
"\n"
"#menu_frame{\n"
"border-top:0.5px solid #4d4d4f;\n"
"}\n"
"\n"
"#menu_frame QPushButton{\n"
"color:#fff;\n"
"border:none;\n"
"padding:5px 10px;\n"
"border-radius:5px;\n"
"background:none\n"
"}\n"
"\n"
"#menu_frame Qframe{\n"
"border-radius:5px;\n"
"}\n"
"\n"
"#new_chat_buttn{\n"
"border:1px solid #4d4d4f;\n"
"color:#fff;\n"
"border-radius:10px;\n"
"padding:5px;\n"
"}\n"
"\n"
"#side_widget,\n"
"chat_list{\n"
"background:#202313\n"
"}\n"
"\n"
"#chat_list::item{\n"
"color:#fff;\n"
"padding:10px;\n"
"border-radius:5px;\n"
"margin-top:5px;\n"
"}\n"
"\n"
"#side_widget QPushButton:hover,\n"
"#chat_list::item:hover,\n"
"#user_frame:hover,\n"
"#menu_frame QComboBox:hover,\n"
"#menu_frame QLabel:hover,\n"
"#menu_frame Qframe:hover{\n"
"background:#2a2b32\n"
"}\n"
"\n"
"\n"
"#side_widget QListView{\n"
"background:#202313;\n"
"border:none;\n"
"}\n"
"\n"
"#new_label{\n"
"padding:5px;\n"
"border-radius:6px;\n"
"background:#fae69e;\n"
"}\n"
"\n"
"#comboBox{\n"
"border:none;\n"
"background:#202313;\n"
"color:#fff;\n"
"padding:0px 10px;\n"
"}\n"
"\n"
"#input_frame{\n"
"border:1px solid #e5e5e5;\n"
"background:#fff;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"#input_textEdit{\n"
"background:#fff;\n"
"border:none;\n"
"}\n"
"\n"
"#send_btn{\n"
"border:none;\n"
"padding:5px;\n"
"border-radius:5px;\n"
"}\n"
"\n"
"#send_btn:hover{\n"
"background:#ececf1;\n"
"}\n"
"\n"
"#main_widget #scrollAreaWidgetContents{\n"
"background:qlineargradient(spread:pad, x1:1, y1:0.369318, x2:0.458, y2:0.398, stop:0 rgba(0, 0, 117, 255), stop:1 rgba(0, 1, 0, 255));\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.side_widget = QtWidgets.QWidget(self.centralwidget)
        self.side_widget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.side_widget.setStyleSheet("")
        self.side_widget.setObjectName("side_widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.side_widget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.new_chat_frame = QtWidgets.QFrame(self.side_widget)
        self.new_chat_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.new_chat_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.new_chat_frame.setObjectName("new_chat_frame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.new_chat_frame)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.new_chat_buttn = QtWidgets.QPushButton(self.new_chat_frame)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.new_chat_buttn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../add.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_chat_buttn.setIcon(icon)
        self.new_chat_buttn.setIconSize(QtCore.QSize(25, 25))
        self.new_chat_buttn.setObjectName("new_chat_buttn")
        self.horizontalLayout_4.addWidget(self.new_chat_buttn)
        self.verticalLayout_2.addWidget(self.new_chat_frame)
        self.chat_list_frame = QtWidgets.QFrame(self.side_widget)
        self.chat_list_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.chat_list_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.chat_list_frame.setObjectName("chat_list_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.chat_list_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.listView = QtWidgets.QListView(self.chat_list_frame)
        self.listView.setObjectName("listView")
        self.gridLayout.addWidget(self.listView, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.chat_list_frame)
        self.menu_frame = QtWidgets.QFrame(self.side_widget)
        self.menu_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu_frame.setObjectName("menu_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.menu_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.menu_frame)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButton_2.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_2.setIcon(icon1)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.menu_frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setMaximumSize(QtCore.QSize(32, 32))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/icons/icons/robot.svg"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.frame_2)
        self.comboBox.setEnabled(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.menu_frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/dark.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout.addWidget(self.frame_3)
        self.verticalLayout_2.addWidget(self.menu_frame)
        self.horizontalLayout_5.addWidget(self.side_widget)
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setEnabled(True)
        font = QtGui.QFont()
        font.setKerning(True)
        self.main_widget.setFont(font)
        self.main_widget.setStyleSheet("")
        self.main_widget.setObjectName("main_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 20)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(107, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(106, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 2, 1, 1)
        self.input_frame = QtWidgets.QFrame(self.main_widget)
        self.input_frame.setEnabled(True)
        self.input_frame.setMinimumSize(QtCore.QSize(650, 0))
        self.input_frame.setMaximumSize(QtCore.QSize(16777215, 100))
        self.input_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.input_frame.setObjectName("input_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.input_frame)
        self.gridLayout_2.setContentsMargins(10, 10, 5, 10)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.input_textEdit = QtWidgets.QTextEdit(self.input_frame)
        self.input_textEdit.setEnabled(True)
        self.input_textEdit.setObjectName("input_textEdit")
        self.gridLayout_2.addWidget(self.input_textEdit, 0, 0, 2, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 45, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.send_btn = QtWidgets.QPushButton(self.input_frame)
        self.send_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/send.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.send_btn.setIcon(icon3)
        self.send_btn.setObjectName("send_btn")
        self.gridLayout_2.addWidget(self.send_btn, 1, 1, 1, 1)
        self.gridLayout_4.addWidget(self.input_frame, 1, 1, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.main_widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 881, 583))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(20, 558, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 3)
        self.horizontalLayout_5.addWidget(self.main_widget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1162, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.new_chat_buttn.setText(_translate("MainWindow", "New Chat"))
        self.pushButton_2.setText(_translate("MainWindow", "Clear Conversation"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Text_based"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Bot_Chacha"))
        self.pushButton_4.setText(_translate("MainWindow", "Dark Mode"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
